//! Manual broad comparison of the beam-width-one combat resolver and production Oracle.
//!
//! Run with:
//! `cargo test -p mk-engine --release greedy_vs_oracle_broad_diagnostic -- --ignored --nocapture`
//!
//! Replay artifacts generated by `generate_replays.py --artifact` contain filtered
//! client states rather than lossless `GameState` snapshots. Their observed enemy/hand
//! combinations inform these fixtures, but every case is constructed as a valid engine
//! state so both resolvers receive identical hidden state and legal actions.

use std::collections::BTreeMap;
use std::time::{Duration, Instant};

use mk_engine::action_pipeline::apply_legal_action;
use mk_engine::combat::execute_enter_combat;
use mk_engine::combat_search::{
    search_combat, search_combat_greedy, CombatSearchConfig, CombatSearchResult, GreedyCombatConfig,
};
use mk_engine::effect_queue::WOUND_CARD_ID;
use mk_engine::legal_actions::enumerate_legal_actions;
use mk_engine::setup::create_solo_game;
use mk_engine::undo::UndoStack;
use mk_types::enums::{CombatPhase, Hero, ManaColor, RoundPhase, SidewaysAs, UnitState};
use mk_types::ids::{CardId, EnemyTokenId, SourceDieId, UnitId, UnitInstanceId};
use mk_types::legal_action::LegalAction;
use mk_types::state::{Crystals, GameState, PlayerUnit, SourceDie};

const E_DIGGERS_1: &str = "diggers_1";
const E_DIGGERS_2: &str = "diggers_2";
const E_PROWLERS_1: &str = "prowlers_1";
const E_PROWLERS_2: &str = "prowlers_2";
const E_CURSED_HAGS_1: &str = "cursed_hags_1";
const E_WOLF_RIDERS_1: &str = "wolf_riders_1";
const E_IRONCLADS_1: &str = "ironclads_1";
const E_ORC_SUMMONERS_1: &str = "orc_summoners_1";
const E_CENTAUR_OUTRIDERS_1: &str = "centaur_outriders_1";
const E_ORC_SKIRMISHERS_1: &str = "orc_skirmishers_1";
const E_ORC_STONETHROWERS_1: &str = "orc_stonethrowers_1";
const E_ORC_TRACKER_1: &str = "orc_tracker_1";
const E_SKELETAL_WARRIORS_1: &str = "skeletal_warriors_1";
const E_CORRUPTED_PRIESTS_1: &str = "corrupted_priests_1";
const E_ELEMENTAL_PRIESTS_1: &str = "elemental_priests_1";
const E_CLOUD_GRIFFONS_1: &str = "cloud_griffons_1";
const E_CRYSTAL_SPRITES_1: &str = "crystal_sprites_1";
const E_SWORDSMEN_1: &str = "swordsmen_1";
const E_ICE_GOLEMS_1: &str = "ice_golems_1";
const E_FIRE_GOLEMS_1: &str = "fire_golems_1";
const E_FIRE_ELEMENTAL_1: &str = "fire_elemental_1";

const C_RAGE: &str = "rage";
const C_DETERMINATION: &str = "determination";
const C_STAMINA: &str = "stamina";
const C_MARCH: &str = "march";
const C_SWIFTNESS: &str = "swiftness";
const C_IMPROVISATION: &str = "improvisation";
const C_CONCENTRATION: &str = "concentration";
const C_PROMISE: &str = "promise";
const C_BATTLE_VERSATILITY: &str = "arythea_battle_versatility";
const C_BLOOD_RAGE: &str = "blood_rage";
const C_ICE_BOLT: &str = "ice_bolt";
const C_FIREBALL: &str = "fireball";
const C_SWORD_OF_JUSTICE: &str = "sword_of_justice";
const C_HEROIC_TALE: &str = "heroic_tale";

const U_PEASANTS: &str = "peasants";
const U_FORESTERS: &str = "foresters";
const U_UTEM_CROSSBOWMEN: &str = "utem_crossbowmen";
const U_UTEM_GUARDSMEN: &str = "utem_guardsmen";
const U_UTEM_SWORDSMEN: &str = "utem_swordsmen";

const SOURCE_DIE_RED: &str = "diagnostic_die_red";
const SOURCE_DIE_BLUE: &str = "diagnostic_die_blue";
const SOURCE_DIE_WHITE: &str = "diagnostic_die_white";

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Difficulty {
    Easy,
    Medium,
    Hard,
    Mixed,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum HandStrength {
    Weak,
    Balanced,
    Strong,
    Preserve,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum PhaseTag {
    RangedSiege,
    Block,
    AssignDamage,
    Attack,
}

impl PhaseTag {
    fn combat_phase(self) -> CombatPhase {
        match self {
            Self::RangedSiege => CombatPhase::RangedSiege,
            Self::Block => CombatPhase::Block,
            Self::AssignDamage => CombatPhase::AssignDamage,
            Self::Attack => CombatPhase::Attack,
        }
    }

    fn decision_phase_count(self) -> usize {
        match self {
            Self::RangedSiege => 4,
            Self::Block => 3,
            Self::AssignDamage => 2,
            Self::Attack => 1,
        }
    }
}

#[derive(Debug, Clone)]
struct FixtureSpec {
    name: &'static str,
    difficulty: Difficulty,
    hand_strength: HandStrength,
    phase: PhaseTag,
    enemies: &'static [&'static str],
    hand: &'static [&'static str],
    units: &'static [&'static str],
    crystals: [u8; 4],
    fortified: bool,
    source_depleted: bool,
    blocking_relevant: bool,
    card_preservation_relevant: bool,
}

#[derive(Debug)]
struct DiagnosticRecord {
    spec: FixtureSpec,
    oracle: CombatSearchResult,
    greedy: CombatSearchResult,
    oracle_elapsed: Duration,
    greedy_elapsed: Duration,
    first_action_match: bool,
    signed_error: f64,
    oracle_blocks: bool,
    greedy_blocks: bool,
    oracle_remaining_hand: Vec<String>,
    greedy_remaining_hand: Vec<String>,
    oracle_combat_remaining: usize,
    greedy_combat_remaining: usize,
}

fn fixture(
    name: &'static str,
    difficulty: Difficulty,
    hand_strength: HandStrength,
    phase: PhaseTag,
    enemies: &'static [&'static str],
    hand: &'static [&'static str],
) -> FixtureSpec {
    FixtureSpec {
        name,
        difficulty,
        hand_strength,
        phase,
        enemies,
        hand,
        units: &[],
        crystals: [0; 4],
        fortified: false,
        source_depleted: false,
        blocking_relevant: matches!(phase, PhaseTag::Block | PhaseTag::AssignDamage),
        card_preservation_relevant: hand_strength == HandStrength::Preserve,
    }
}

fn representative_fixtures() -> Vec<FixtureSpec> {
    use Difficulty::{Easy, Hard, Medium, Mixed};
    use HandStrength::{Balanced, Preserve, Strong, Weak};
    use PhaseTag::{AssignDamage, Attack, Block, RangedSiege};

    let mut fixtures = vec![
        fixture(
            "easy_diggers_ranged_strong",
            Easy,
            Strong,
            RangedSiege,
            &[E_DIGGERS_1],
            &[C_SWIFTNESS, C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "easy_diggers_block_weak",
            Easy,
            Weak,
            Block,
            &[E_DIGGERS_1],
            &[C_DETERMINATION, C_STAMINA, C_PROMISE],
        ),
        fixture(
            "easy_prowlers_block_balanced",
            Easy,
            Balanced,
            Block,
            &[E_PROWLERS_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "easy_crystal_sprites_attack",
            Easy,
            Balanced,
            Attack,
            &[E_CRYSTAL_SPRITES_1],
            &[C_RAGE, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "easy_skeletal_attack_weak",
            Easy,
            Weak,
            Attack,
            &[E_SKELETAL_WARRIORS_1],
            &[C_RAGE, C_MARCH, C_PROMISE],
        ),
        fixture(
            "easy_diggers_preserve_artifact",
            Easy,
            Preserve,
            Attack,
            &[E_DIGGERS_1],
            &[C_SWORD_OF_JUSTICE, C_RAGE, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "easy_prowlers_unit_damage",
            Easy,
            Balanced,
            AssignDamage,
            &[E_PROWLERS_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "easy_wolf_rider_block_strong",
            Easy,
            Strong,
            Block,
            &[E_WOLF_RIDERS_1],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "easy_skirmisher_multiattack_block",
            Easy,
            Balanced,
            Block,
            &[E_ORC_SKIRMISHERS_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "easy_diggers_depleted_attack",
            Easy,
            Weak,
            Attack,
            &[E_DIGGERS_1],
            &[C_RAGE, C_MARCH, WOUND_CARD_ID],
        ),
        fixture(
            "medium_cursed_hags_block",
            Medium,
            Balanced,
            Block,
            &[E_CURSED_HAGS_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "medium_wolf_rider_ranged",
            Medium,
            Strong,
            RangedSiege,
            &[E_WOLF_RIDERS_1],
            &[C_SWIFTNESS, C_ICE_BOLT, C_RAGE, C_DETERMINATION, C_STAMINA],
        ),
        fixture(
            "medium_centaur_ranged",
            Medium,
            Balanced,
            RangedSiege,
            &[E_CENTAUR_OUTRIDERS_1],
            &[C_SWIFTNESS, C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "medium_ironclads_attack_resistance",
            Medium,
            Strong,
            Attack,
            &[E_IRONCLADS_1],
            &[
                C_BLOOD_RAGE,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "medium_fire_elemental_ranged",
            Medium,
            Strong,
            RangedSiege,
            &[E_FIRE_ELEMENTAL_1],
            &[C_ICE_BOLT, C_FIREBALL, C_RAGE, C_DETERMINATION, C_STAMINA],
        ),
        fixture(
            "medium_ice_golem_attack",
            Medium,
            Balanced,
            Attack,
            &[E_ICE_GOLEMS_1],
            &[C_FIREBALL, C_RAGE, C_IMPROVISATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "medium_orc_tracker_block",
            Medium,
            Balanced,
            Block,
            &[E_ORC_TRACKER_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_SWIFTNESS, C_MARCH],
        ),
        fixture(
            "medium_two_prowlers_block",
            Medium,
            Strong,
            Block,
            &[E_PROWLERS_1, E_PROWLERS_2],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "medium_two_diggers_attack",
            Medium,
            Balanced,
            Attack,
            &[E_DIGGERS_1, E_DIGGERS_2],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "medium_preserve_fireball_block",
            Medium,
            Preserve,
            Block,
            &[E_WOLF_RIDERS_1],
            &[
                C_FIREBALL,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
            ],
        ),
        fixture(
            "hard_swordsmen_block_unit",
            Hard,
            Strong,
            Block,
            &[E_SWORDSMEN_1],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "hard_stonethrower_block",
            Hard,
            Balanced,
            Block,
            &[E_ORC_STONETHROWERS_1],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "hard_elemental_priests_block",
            Hard,
            Strong,
            Block,
            &[E_ELEMENTAL_PRIESTS_1],
            &[
                C_FIREBALL,
                C_ICE_BOLT,
                C_DETERMINATION,
                C_STAMINA,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "hard_cloud_griffon_ranged",
            Hard,
            Strong,
            RangedSiege,
            &[E_CLOUD_GRIFFONS_1],
            &[
                C_SWIFTNESS,
                C_ICE_BOLT,
                C_FIREBALL,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "hard_corrupted_priest_attack",
            Hard,
            Strong,
            Attack,
            &[E_CORRUPTED_PRIESTS_1],
            &[
                C_BLOOD_RAGE,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "hard_ironclads_hags_attack",
            Hard,
            Strong,
            Attack,
            &[E_IRONCLADS_1, E_CURSED_HAGS_1],
            &[
                C_BLOOD_RAGE,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
            ],
        ),
        fixture(
            "hard_wolf_ironclad_block",
            Hard,
            Strong,
            Block,
            &[E_WOLF_RIDERS_1, E_IRONCLADS_1],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "hard_fortified_ironclad_ranged",
            Hard,
            Strong,
            RangedSiege,
            &[E_IRONCLADS_1],
            &[
                C_FIREBALL,
                C_ICE_BOLT,
                C_SWORD_OF_JUSTICE,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "hard_preserve_sword_block",
            Hard,
            Preserve,
            Block,
            &[E_SWORDSMEN_1],
            &[
                C_SWORD_OF_JUSTICE,
                C_HEROIC_TALE,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
            ],
        ),
        fixture(
            "hard_swordsmen_attack_weak",
            Hard,
            Weak,
            Attack,
            &[E_SWORDSMEN_1],
            &[C_RAGE, C_MARCH, C_STAMINA, WOUND_CARD_ID],
        ),
        fixture(
            "mixed_diggers_prowlers_ranged",
            Mixed,
            Balanced,
            RangedSiege,
            &[E_DIGGERS_1, E_PROWLERS_1],
            &[C_SWIFTNESS, C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH],
        ),
        fixture(
            "mixed_three_green_block",
            Mixed,
            Strong,
            Block,
            &[E_DIGGERS_1, E_WOLF_RIDERS_1, E_ORC_SKIRMISHERS_1],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "mixed_summoner_diggers_block",
            Mixed,
            Strong,
            Block,
            &[E_ORC_SUMMONERS_1, E_DIGGERS_1],
            &[
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_IMPROVISATION,
            ],
        ),
        fixture(
            "mixed_fire_ice_golems_attack",
            Mixed,
            Strong,
            Attack,
            &[E_FIRE_GOLEMS_1, E_ICE_GOLEMS_1],
            &[
                C_FIREBALL,
                C_ICE_BOLT,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "mixed_elemental_ironclad_ranged",
            Mixed,
            Strong,
            RangedSiege,
            &[E_FIRE_ELEMENTAL_1, E_IRONCLADS_1],
            &[
                C_FIREBALL,
                C_ICE_BOLT,
                C_SWORD_OF_JUSTICE,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "mixed_two_prowlers_unit_damage",
            Mixed,
            Strong,
            AssignDamage,
            &[E_PROWLERS_1, E_PROWLERS_2],
            &[C_RAGE, C_DETERMINATION, C_STAMINA, C_MARCH, C_SWIFTNESS],
        ),
        fixture(
            "mixed_three_enemy_attack",
            Mixed,
            Strong,
            Attack,
            &[E_DIGGERS_1, E_PROWLERS_1, E_WOLF_RIDERS_1],
            &[
                C_BLOOD_RAGE,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
            ],
        ),
        fixture(
            "mixed_three_enemy_preserve",
            Mixed,
            Preserve,
            Block,
            &[E_DIGGERS_1, E_PROWLERS_1, E_WOLF_RIDERS_1],
            &[
                C_SWORD_OF_JUSTICE,
                C_FIREBALL,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
            ],
        ),
        fixture(
            "mixed_fortified_pair_ranged",
            Mixed,
            Strong,
            RangedSiege,
            &[E_DIGGERS_1, E_IRONCLADS_1],
            &[
                C_FIREBALL,
                C_ICE_BOLT,
                C_SWORD_OF_JUSTICE,
                C_RAGE,
                C_DETERMINATION,
                C_STAMINA,
            ],
        ),
        fixture(
            "mixed_four_easy_attack",
            Mixed,
            Strong,
            Attack,
            &[E_DIGGERS_1, E_DIGGERS_2, E_PROWLERS_1, E_PROWLERS_2],
            &[
                C_BLOOD_RAGE,
                C_RAGE,
                C_IMPROVISATION,
                C_CONCENTRATION,
                C_STAMINA,
                C_MARCH,
                C_SWIFTNESS,
                C_BATTLE_VERSATILITY,
            ],
        ),
    ];

    fixtures[6].units = &[U_PEASANTS];
    fixtures[6].blocking_relevant = true;
    fixtures[9].source_depleted = true;
    fixtures[11].crystals = [0, 2, 0, 1];
    fixtures[13].crystals = [2, 0, 0, 0];
    fixtures[14].crystals = [1, 2, 0, 0];
    fixtures[15].crystals = [2, 1, 0, 0];
    fixtures[20].units = &[U_UTEM_GUARDSMEN];
    fixtures[22].crystals = [2, 2, 0, 0];
    fixtures[23].units = &[U_UTEM_CROSSBOWMEN];
    fixtures[27].fortified = true;
    fixtures[27].crystals = [1, 2, 0, 1];
    fixtures[28].units = &[U_UTEM_SWORDSMEN];
    fixtures[33].crystals = [2, 2, 0, 0];
    fixtures[34].fortified = true;
    fixtures[34].crystals = [1, 2, 0, 1];
    fixtures[35].units = &[U_PEASANTS, U_FORESTERS];
    fixtures[37].units = &[U_UTEM_SWORDSMEN];
    fixtures[38].fortified = true;
    fixtures[38].crystals = [1, 2, 0, 1];
    fixtures
}

fn add_units(state: &mut GameState, unit_ids: &[&str]) {
    for &unit_name in unit_ids {
        let definition = mk_data::units::get_unit(unit_name).expect("diagnostic unit must exist");
        let instance_id =
            UnitInstanceId::from(format!("diagnostic_unit_{}", state.next_instance_counter));
        state.next_instance_counter += 1;
        state.players[0].units.push(PlayerUnit {
            instance_id,
            unit_id: UnitId::from(unit_name),
            level: definition.level,
            state: UnitState::Ready,
            wounded: false,
            used_resistance_this_combat: false,
            used_ability_indices: Vec::new(),
            mana_token: None,
        });
    }
}

fn apply_action(state: &mut GameState, action: &LegalAction) {
    let epoch = state.action_epoch;
    apply_legal_action(state, &mut UndoStack::new(), 0, action, epoch)
        .expect("diagnostic fixture action must apply");
}

fn advance_to_phase(state: &mut GameState, target: CombatPhase) {
    while state
        .combat
        .as_ref()
        .is_some_and(|combat| combat.phase != target)
    {
        let phase = state.combat.as_ref().unwrap().phase;
        let actions = enumerate_legal_actions(state, 0);
        let action = if phase == CombatPhase::AssignDamage {
            actions
                .actions
                .iter()
                .find(|action| matches!(action, LegalAction::AssignDamageToHero { .. }))
                .or_else(|| {
                    actions
                        .actions
                        .iter()
                        .find(|action| matches!(action, LegalAction::EndCombatPhase))
                })
        } else {
            actions
                .actions
                .iter()
                .find(|action| matches!(action, LegalAction::EndCombatPhase))
        }
        .unwrap_or_else(|| panic!("cannot advance diagnostic fixture from {phase:?} to {target:?}"))
        .clone();
        apply_action(state, &action);
    }
}

fn build_state(spec: &FixtureSpec, seed: u32) -> GameState {
    let mut state = create_solo_game(seed, Hero::Arythea);
    state.round_phase = RoundPhase::PlayerTurns;
    state.players[0].hand = spec.hand.iter().map(|&card| CardId::from(card)).collect();
    state.players[0].crystals = Crystals {
        red: spec.crystals[0],
        blue: spec.crystals[1],
        green: spec.crystals[2],
        white: spec.crystals[3],
    };
    state.source.dice = vec![
        SourceDie {
            id: SourceDieId::from(SOURCE_DIE_RED),
            color: ManaColor::Red,
            is_depleted: spec.source_depleted,
            taken_by_player_id: None,
        },
        SourceDie {
            id: SourceDieId::from(SOURCE_DIE_BLUE),
            color: ManaColor::Blue,
            is_depleted: spec.source_depleted,
            taken_by_player_id: None,
        },
        SourceDie {
            id: SourceDieId::from(SOURCE_DIE_WHITE),
            color: ManaColor::White,
            is_depleted: spec.source_depleted,
            taken_by_player_id: None,
        },
    ];
    add_units(&mut state, spec.units);

    let tokens: Vec<EnemyTokenId> = spec
        .enemies
        .iter()
        .map(|&enemy| EnemyTokenId::from(enemy))
        .collect();
    execute_enter_combat(
        &mut state,
        0,
        &tokens,
        spec.fortified,
        None,
        Default::default(),
    )
    .expect("diagnostic fixture must enter combat");
    advance_to_phase(&mut state, spec.phase.combat_phase());
    state
}

fn replay(state: &GameState, actions: &[LegalAction]) -> GameState {
    let mut result = state.clone();
    for action in actions {
        apply_action(&mut result, action);
    }
    result
}

fn has_block_action(actions: &[LegalAction]) -> bool {
    actions.iter().any(|action| {
        matches!(
            action,
            LegalAction::DeclareBlock { .. }
                | LegalAction::PlayCardSideways {
                    sideways_as: SidewaysAs::Block,
                    ..
                }
        )
    })
}

fn combat_remaining(state: &GameState) -> usize {
    state
        .combat
        .as_ref()
        .map(|combat| {
            combat
                .enemies
                .iter()
                .filter(|enemy| !enemy.is_defeated)
                .count()
        })
        .unwrap_or(0)
}

fn remaining_hand(state: &GameState) -> Vec<String> {
    state.players[0]
        .hand
        .iter()
        .map(ToString::to_string)
        .collect()
}

fn mean(values: impl Iterator<Item = f64>) -> f64 {
    let values: Vec<f64> = values.collect();
    if values.is_empty() {
        return 0.0;
    }
    values.iter().sum::<f64>() / values.len() as f64
}

fn print_boolean_group(
    records: &[DiagnosticRecord],
    label: &str,
    predicate: impl Fn(&DiagnosticRecord) -> bool,
) {
    for selected in [true, false] {
        let group: Vec<&DiagnosticRecord> = records
            .iter()
            .filter(|record| predicate(record) == selected)
            .collect();
        println!(
            "BIAS\t{label}\t{selected}\tcount={}\tmean_signed={:.2}\tmean_abs={:.2}\tmatch_rate={:.3}",
            group.len(),
            mean(group.iter().map(|record| record.signed_error)),
            mean(group.iter().map(|record| record.signed_error.abs())),
            mean(group.iter().map(|record| f64::from(record.first_action_match))),
        );
    }
}

fn print_numeric_group(
    records: &[DiagnosticRecord],
    label: &str,
    key: impl Fn(&DiagnosticRecord) -> usize,
) {
    let mut groups: BTreeMap<usize, Vec<&DiagnosticRecord>> = BTreeMap::new();
    for record in records {
        groups.entry(key(record)).or_default().push(record);
    }
    for (value, group) in groups {
        println!(
            "GROUP\t{label}\t{value}\tcount={}\tmean_signed={:.2}\tmean_abs={:.2}\tmatch_rate={:.3}",
            group.len(),
            mean(group.iter().map(|record| record.signed_error)),
            mean(group.iter().map(|record| record.signed_error.abs())),
            mean(group.iter().map(|record| f64::from(record.first_action_match))),
        );
    }
}

fn print_category_group(
    records: &[DiagnosticRecord],
    label: &str,
    key: impl Fn(&DiagnosticRecord) -> String,
) {
    let mut groups: BTreeMap<String, Vec<&DiagnosticRecord>> = BTreeMap::new();
    for record in records {
        groups.entry(key(record)).or_default().push(record);
    }
    for (value, group) in groups {
        println!(
            "GROUP\t{label}\t{value}\tcount={}\tmean_signed={:.2}\tmean_abs={:.2}\tmatch_rate={:.3}",
            group.len(),
            mean(group.iter().map(|record| record.signed_error)),
            mean(group.iter().map(|record| record.signed_error.abs())),
            mean(group.iter().map(|record| f64::from(record.first_action_match))),
        );
    }
}

#[test]
#[ignore = "manual 40-fixture Oracle comparison"]
fn greedy_vs_oracle_broad_diagnostic() {
    let fixtures = representative_fixtures();
    assert_eq!(fixtures.len(), 40);
    let oracle_config = CombatSearchConfig {
        node_limit: 1_000_000,
        seed_rollouts: 500,
        ..CombatSearchConfig::default()
    };
    let greedy_config = GreedyCombatConfig::default();
    let mut records = Vec::with_capacity(fixtures.len());

    println!("fixture\tdifficulty\thand_strength\tphase\tenemies\thand_size\tdecision_phases\tblocking_tag\tpreservation_tag\toracle_blocks\tgreedy_blocks\tfirst_match\tsigned_error\toracle_score\tgreedy_score\toracle_fame\tgreedy_fame\toracle_wounds\tgreedy_wounds\toracle_cards\tgreedy_cards\toracle_complete\toracle_nodes\tgreedy_nodes\toracle_ms\tgreedy_ms\toracle_first\tgreedy_first");
    for (index, spec) in fixtures.into_iter().enumerate() {
        let state = build_state(&spec, 10_000 + index as u32);

        let started = Instant::now();
        let oracle = search_combat(&state, &oracle_config);
        let oracle_elapsed = started.elapsed();
        let started = Instant::now();
        let greedy = search_combat_greedy(&state, &greedy_config)
            .unwrap_or_else(|error| panic!("{}: greedy resolver failed: {error}", spec.name));
        let greedy_elapsed = started.elapsed();

        let oracle_state = replay(&state, &oracle.actions);
        let greedy_state = replay(&state, &greedy.actions);
        let first_action_match = oracle.actions.first() == greedy.actions.first();
        let signed_error = oracle.score - greedy.score;
        let oracle_blocks = has_block_action(&oracle.actions);
        let greedy_blocks = has_block_action(&greedy.actions);

        println!(
            "{}\t{:?}\t{:?}\t{:?}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{:.2}\t{:.2}\t{:.2}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{}\t{:.3}\t{:.3}\t{:?}\t{:?}",
            spec.name,
            spec.difficulty,
            spec.hand_strength,
            spec.phase,
            spec.enemies.len(),
            spec.hand.len(),
            spec.phase.decision_phase_count(),
            spec.blocking_relevant,
            spec.card_preservation_relevant,
            oracle_blocks,
            greedy_blocks,
            first_action_match,
            signed_error,
            oracle.score,
            greedy.score,
            oracle.fame_gained,
            greedy.fame_gained,
            oracle.wounds_taken,
            greedy.wounds_taken,
            oracle.cards_remaining,
            greedy.cards_remaining,
            oracle.complete,
            oracle.nodes_visited,
            greedy.nodes_visited,
            oracle_elapsed.as_secs_f64() * 1_000.0,
            greedy_elapsed.as_secs_f64() * 1_000.0,
            oracle.actions.first(),
            greedy.actions.first(),
        );

        records.push(DiagnosticRecord {
            spec,
            oracle,
            greedy,
            oracle_elapsed,
            greedy_elapsed,
            first_action_match,
            signed_error,
            oracle_blocks,
            greedy_blocks,
            oracle_remaining_hand: remaining_hand(&oracle_state),
            greedy_remaining_hand: remaining_hand(&greedy_state),
            oracle_combat_remaining: combat_remaining(&oracle_state),
            greedy_combat_remaining: combat_remaining(&greedy_state),
        });
    }

    println!(
        "SUMMARY\tcount={}\toracle_complete={}\tfirst_match_rate={:.3}\tmean_signed={:.2}\tmean_abs={:.2}\toracle_ms={:.2}\tgreedy_ms={:.2}\tspeed_ratio={:.1}",
        records.len(),
        records.iter().filter(|record| record.oracle.complete).count(),
        mean(records.iter().map(|record| f64::from(record.first_action_match))),
        mean(records.iter().map(|record| record.signed_error)),
        mean(records.iter().map(|record| record.signed_error.abs())),
        records.iter().map(|record| record.oracle_elapsed.as_secs_f64()).sum::<f64>() * 1_000.0,
        records.iter().map(|record| record.greedy_elapsed.as_secs_f64()).sum::<f64>() * 1_000.0,
        records.iter().map(|record| record.oracle_elapsed.as_secs_f64()).sum::<f64>()
            / records.iter().map(|record| record.greedy_elapsed.as_secs_f64()).sum::<f64>(),
    );
    print_boolean_group(&records, "blocking_tag", |record| {
        record.spec.blocking_relevant
    });
    print_boolean_group(&records, "oracle_blocks_greedy_skips", |record| {
        record.oracle_blocks && !record.greedy_blocks
    });
    print_boolean_group(&records, "preservation_tag", |record| {
        record.spec.card_preservation_relevant
    });
    print_category_group(&records, "difficulty", |record| {
        format!("{:?}", record.spec.difficulty)
    });
    print_category_group(&records, "hand_strength", |record| {
        format!("{:?}", record.spec.hand_strength)
    });
    print_category_group(&records, "phase", |record| {
        format!("{:?}", record.spec.phase)
    });
    print_numeric_group(&records, "enemy_count", |record| record.spec.enemies.len());
    print_numeric_group(&records, "hand_size", |record| record.spec.hand.len());
    print_numeric_group(&records, "decision_phases", |record| {
        record.spec.phase.decision_phase_count()
    });

    for record in records
        .iter()
        .filter(|record| record.oracle_blocks && !record.greedy_blocks)
    {
        println!(
            "SKIP\tfixture={}\ttags={:?}/{:?}/{:?}\tsigned_error={:.2}\toracle_outcome=fame:{} wounds:{} cards:{} crystals:{} units:{} ko:{}\tgreedy_outcome=fame:{} wounds:{} cards:{} crystals:{} units:{} ko:{}\toracle_path={:?}\tgreedy_path={:?}",
            record.spec.name,
            record.spec.difficulty,
            record.spec.hand_strength,
            record.spec.phase,
            record.signed_error,
            record.oracle.fame_gained,
            record.oracle.wounds_taken,
            record.oracle.cards_remaining,
            record.oracle.crystals_spent,
            record.oracle.units_newly_wounded,
            record.oracle.knocked_out,
            record.greedy.fame_gained,
            record.greedy.wounds_taken,
            record.greedy.cards_remaining,
            record.greedy.crystals_spent,
            record.greedy.units_newly_wounded,
            record.greedy.knocked_out,
            record.oracle.actions,
            record.greedy.actions,
        );
    }

    records.sort_by(|left, right| right.signed_error.abs().total_cmp(&left.signed_error.abs()));
    for (rank, record) in records.iter().take(5).enumerate() {
        println!(
            "WORST\trank={}\tfixture={}\ttags={:?}/{:?}/{:?}\tsigned_error={:.2}\toracle_first={:?}\tgreedy_first={:?}\toracle_outcome=fame:{} wounds:{} cards:{} crystals:{} units:{} ko:{} remaining_enemies:{} hand:{:?}\tgreedy_outcome=fame:{} wounds:{} cards:{} crystals:{} units:{} ko:{} remaining_enemies:{} hand:{:?}\toracle_path={:?}\tgreedy_path={:?}",
            rank + 1,
            record.spec.name,
            record.spec.difficulty,
            record.spec.hand_strength,
            record.spec.phase,
            record.signed_error,
            record.oracle.actions.first(),
            record.greedy.actions.first(),
            record.oracle.fame_gained,
            record.oracle.wounds_taken,
            record.oracle.cards_remaining,
            record.oracle.crystals_spent,
            record.oracle.units_newly_wounded,
            record.oracle.knocked_out,
            record.oracle_combat_remaining,
            record.oracle_remaining_hand,
            record.greedy.fame_gained,
            record.greedy.wounds_taken,
            record.greedy.cards_remaining,
            record.greedy.crystals_spent,
            record.greedy.units_newly_wounded,
            record.greedy.knocked_out,
            record.greedy_combat_remaining,
            record.greedy_remaining_hand,
            record.oracle.actions,
            record.greedy.actions,
        );
    }
}
